# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sonic.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 734)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1111, 691))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imagem/FundoSonic.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_Sonic = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Sonic.setGeometry(QtCore.QRect(80, 220, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(26)
        self.pushButton_Sonic.setFont(font)
        self.pushButton_Sonic.setStyleSheet("background-color: #55007f;\n"
"color: #ffff00;")
        self.pushButton_Sonic.setObjectName("pushButton_Sonic")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 70, 561, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("Color: rgb(255, 85, 0);")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.pushButton_Tails = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Tails.setGeometry(QtCore.QRect(80, 310, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(26)
        self.pushButton_Tails.setFont(font)
        self.pushButton_Tails.setStyleSheet("background-color: #55007f;\n"
"color: #ffff00;")
        self.pushButton_Tails.setObjectName("pushButton_Tails")
        self.pushButton_Amy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Amy.setGeometry(QtCore.QRect(80, 480, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(26)
        self.pushButton_Amy.setFont(font)
        self.pushButton_Amy.setStyleSheet("background-color: #55007f;\n"
"color: #ffff00;")
        self.pushButton_Amy.setObjectName("pushButton_Amy")
        self.pushButton_Knuckles = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Knuckles.setGeometry(QtCore.QRect(80, 390, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(26)
        self.pushButton_Knuckles.setFont(font)
        self.pushButton_Knuckles.setStyleSheet("background-color: #55007f;\n"
"color: #ffff00;")
        self.pushButton_Knuckles.setObjectName("pushButton_Knuckles")
        self.pushButton_Eggman = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Eggman.setGeometry(QtCore.QRect(890, 380, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(26)
        self.pushButton_Eggman.setFont(font)
        self.pushButton_Eggman.setAutoFillBackground(False)
        self.pushButton_Eggman.setStyleSheet("background-color: #55007f;\n"
"color: #ffff00;")
        self.pushButton_Eggman.setAutoDefault(False)
        self.pushButton_Eggman.setObjectName("pushButton_Eggman")
        self.pushButton_Shadow = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Shadow.setGeometry(QtCore.QRect(890, 280, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(26)
        self.pushButton_Shadow.setFont(font)
        self.pushButton_Shadow.setStyleSheet("background-color: #55007f;\n"
"color: #ffff00;")
        self.pushButton_Shadow.setObjectName("pushButton_Shadow")
        self.pushButton_Play = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Play.setGeometry(QtCore.QRect(470, 610, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(26)
        self.pushButton_Play.setFont(font)
        self.pushButton_Play.setStyleSheet("background-color:#ffff00;\n"
"color: #55007f;\n"
"\n"
"")
        self.pushButton_Play.setObjectName("pushButton_Play")
        self.label_PersonagemSelecionado = QtWidgets.QLabel(self.centralwidget)
        self.label_PersonagemSelecionado.setGeometry(QtCore.QRect(440, 280, 231, 271))
        self.label_PersonagemSelecionado.setText("")
        self.label_PersonagemSelecionado.setScaledContents(True)
        self.label_PersonagemSelecionado.setObjectName("label_PersonagemSelecionado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Sonic.setText(_translate("MainWindow", "Sonic"))
        self.label_2.setText(_translate("MainWindow", "Escolha seu Personagem:"))
        self.pushButton_Tails.setText(_translate("MainWindow", "Tails"))
        self.pushButton_Amy.setText(_translate("MainWindow", "Amy"))
        self.pushButton_Knuckles.setText(_translate("MainWindow", "Knuckles"))
        self.pushButton_Eggman.setText(_translate("MainWindow", "Dr. Eggman"))
        self.pushButton_Shadow.setText(_translate("MainWindow", "Shadow"))
        self.pushButton_Play.setText(_translate("MainWindow", "Play"))
